export interface Article {
  id: string;
  title: string;
  category: 'mecanisme' | 'piege' | 'temoignage' | 'exercice';
  categoryLabel: string;
  icon: string;
  readTime: string;
  image?: string;
  content: string[];
}

import { IMAGES } from './images';

export const CATEGORIES = [
  { key: 'all', labelKey: 'library.all', icon: 'grid-outline' },
  { key: 'mecanisme', labelKey: 'library.understand', icon: 'brain-outline' },
  { key: 'piege', labelKey: 'library.traps', icon: 'warning-outline' },
  { key: 'temoignage', labelKey: 'library.stories', icon: 'people-outline' },
  { key: 'exercice', labelKey: 'library.exercises', icon: 'barbell-outline' },
];

export const ARTICLES: Article[] = [
  {
    id: '1',
    title: "Comment fonctionne l'addiction au jeu",
    category: 'mecanisme',
    categoryLabel: 'Comprendre',
    icon: 'brain-outline',
    readTime: '4 min',
    image: IMAGES.articles.brain,
    content: [
      "Le jeu active le circuit de la récompense dans ton cerveau — le même que la nourriture, le sexe ou les drogues. Quand tu joues, ton cerveau libère de la dopamine, le neurotransmetteur du plaisir.",
      "Le problème : avec le temps, ton cerveau s'habitue. Il lui faut des doses de plus en plus fortes pour ressentir le même plaisir. C'est la tolérance. Tu joues plus, tu mises plus, tu restes plus longtemps.",
      "L'addiction n'est pas un manque de volonté. C'est une modification physique du cerveau. Les circuits de décision et de contrôle sont littéralement détournés par le circuit de la récompense.",
      "La bonne nouvelle : le cerveau est plastique. En arrêtant de jouer, les circuits se réparent progressivement. Les premières semaines sont les plus dures, puis ça s'améliore. Chaque jour compte.",
    ],
  },
  {
    id: '2',
    title: "L'illusion de contrôle",
    category: 'piege',
    categoryLabel: 'Pièges mentaux',
    icon: 'warning-outline',
    readTime: '3 min',
    image: IMAGES.articles.trigger,
    content: [
      "« Je connais la machine », « J'ai un système », « Je sens que ça va payer »… L'illusion de contrôle est le piège numéro 1 du joueur.",
      "En réalité, chaque tour de roulette, chaque main de blackjack, chaque tour de machine est INDÉPENDANT du précédent. Le casino n'a pas de mémoire. La bille ne « doit » rien à personne.",
      "Les casinos encouragent cette illusion : ils te laissent choisir tes numéros, souffler sur les dés, appuyer sur le bouton. Tout ça te donne le sentiment de contrôler quelque chose de totalement aléatoire.",
      "Rappelle-toi : si un système pour gagner existait, le casino aurait fermé. L'avantage mathématique est TOUJOURS du côté de la maison. Toujours.",
    ],
  },
  {
    id: '3',
    title: 'Le piège du « presque gagné »',
    category: 'piege',
    categoryLabel: 'Pièges mentaux',
    icon: 'warning-outline',
    readTime: '3 min',
    image: IMAGES.articles.cycle,
    content: [
      "Tu as 2 cerises sur 3, le numéro juste à côté du tien est sorti, tu avais 20 au blackjack et le croupier a fait 21… Ces « presque gagnés » sont le carburant de l'addiction.",
      "Ton cerveau traite un « presque gagné » presque comme une victoire. La dopamine monte. Tu te dis « j'y étais presque, la prochaine fois c'est la bonne ».",
      "Mais statistiquement, un « presque gagné » n'est pas plus proche d'un gain qu'un échec complet. 2 cerises sur 3, c'est une perte. Point.",
      "Les machines à sous sont CONÇUES pour maximiser les « presque gagnés ». Ce n'est pas de la malchance, c'est du design. Tu es programmé pour continuer.",
    ],
  },
  {
    id: '4',
    title: 'La martingale : pourquoi ça ne marche pas',
    category: 'piege',
    categoryLabel: 'Pièges mentaux',
    icon: 'warning-outline',
    readTime: '3 min',
    image: IMAGES.articles.finance,
    content: [
      "La martingale classique : doubler sa mise après chaque perte pour « se refaire ». Sur le papier, ça semble logique. En pratique, c'est une catastrophe.",
      "Après 7 pertes consécutives à 10 €, ta mise est à 1 280 €. Après 10 pertes : 10 240 €. Et tu n'as « gagné » que 10 €. Le risque est délirant pour un gain ridicule.",
      "De plus, les tables ont des limites de mise maximale. Même avec un budget infini, la martingale bute sur ce plafond. Le casino a pensé à tout.",
      "Aucune stratégie de mise ne peut battre l'avantage mathématique de la maison sur le long terme. C'est un théorème mathématique, pas une opinion.",
    ],
  },
  {
    id: '5',
    title: 'Karim, 34 ans — « 3 ans sans jouer »',
    category: 'temoignage',
    categoryLabel: 'Témoignages',
    icon: 'people-outline',
    readTime: '5 min',
    image: IMAGES.articles.success,
    content: [
      "« J'ai commencé aux machines à sous à 22 ans. Au début c'était pour rigoler avec les potes. En 6 mois, j'y allais seul, tous les jours après le boulot. »",
      "« J'ai perdu mon appart, ma copine, 40 000 euros d'économies. Le pire c'est que même quand je gagnais, je rejouais tout. Le gain n'était jamais assez. »",
      "« Le déclic, c'est quand ma mère m'a prêté 500 euros pour manger et que je les ai joués le soir même. J'ai appelé Joueurs Info Service en pleurant. »",
      "« Aujourd'hui ça fait 3 ans. Les premiers mois ont été l'enfer. Mais chaque semaine ça allait un peu mieux. J'ai retrouvé un appart, j'économise, j'ai une vie. Si j'ai pu le faire, toi aussi. »",
    ],
  },
  {
    id: '6',
    title: "Sofia, 28 ans — « Le poker en ligne m'a tout pris »",
    category: 'temoignage',
    categoryLabel: 'Témoignages',
    icon: 'people-outline',
    readTime: '4 min',
    image: IMAGES.articles.family,
    content: [
      "« Tout le monde pense que les joueurs problématiques c'est des vieux au PMU. Moi j'avais 24 ans, un master, un bon job. Et je jouais au poker en ligne jusqu'à 4h du matin. »",
      "« Je me disais que le poker c'est un jeu d'adresse, pas de hasard. C'est vrai en partie, mais l'addiction s'en fiche. Mon cerveau voulait juste la prochaine main. »",
      "« J'ai perdu 15 000 euros en 8 mois. Je cachais tout à mes proches. J'ai failli perdre mon job à force de dormir 3 heures par nuit. »",
      "« Ce qui m'a sauvée : en parler. À une amie d'abord, puis à un psy spécialisé. La honte m'empêchait de demander de l'aide. Mais la honte, c'est l'outil de l'addiction pour te garder isolé. »",
    ],
  },
  {
    id: '7',
    title: 'Exercice : ta lettre à toi-même',
    category: 'exercice',
    categoryLabel: 'Exercices',
    icon: 'barbell-outline',
    readTime: '10 min',
    image: IMAGES.articles.therapy,
    content: [
      "Prends 10 minutes pour écrire une lettre à toi-même. Cette lettre, tu la reliras quand l'envie sera forte.",
      "Écris pourquoi tu as décidé d'arrêter. Sois précis : qu'est-ce que tu as perdu ? De l'argent, du temps, des relations, ta santé mentale ? Note les montants si tu les connais.",
      "Écris ce que tu veux retrouver. La tranquillité ? La confiance de tes proches ? Pouvoir épargner ? Dormir sans stress ?",
      "Termine par un message d'encouragement pour le « toi du futur » qui aura envie de rejouer. Qu'est-ce que tu voudrais lui dire maintenant, avec les idées claires ?",
      "Conserve cette lettre précieusement. Elle est ton ancre.",
    ],
  },
  {
    id: '8',
    title: 'Exercice : identifier tes déclencheurs',
    category: 'exercice',
    categoryLabel: 'Exercices',
    icon: 'barbell-outline',
    readTime: '8 min',
    image: IMAGES.articles.nature,
    content: [
      "Les envies ne viennent pas de nulle part. Elles sont déclenchées par des situations, des émotions ou des environnements précis. Les identifier, c'est les désarmer.",
      "Fais la liste de tes 5 dernières envies fortes. Pour chacune, note : où étais-tu ? Avec qui ? Quelle heure ? Qu'est-ce que tu ressentais juste avant (ennui, stress, tristesse, excitation) ?",
      "Tu vas probablement voir des patterns. Peut-être que c'est toujours le soir, toujours seul, toujours après une journée stressante.",
      "Pour chaque déclencheur identifié, écris une alternative concrète : « Quand je m'ennuie le soir → j'appelle un ami / je sors marcher / je lance un film ». Le but est d'avoir un plan AVANT que l'envie arrive.",
      "Utilise le journal de l'app pour tracker tes envies au quotidien. Plus tu as de données, plus tes patterns seront clairs.",
    ],
  },
  {
    id: '9',
    title: "L'argent perdu ne reviendra pas",
    category: 'piege',
    categoryLabel: 'Pièges mentaux',
    icon: 'warning-outline',
    readTime: '3 min',
    image: IMAGES.articles.finance,
    content: [
      "« Je dois me refaire » — c'est la phrase la plus dangereuse du joueur. L'idée que tu peux récupérer l'argent perdu en jouant encore.",
      "En psychologie, on appelle ça l'aversion à la perte. Perdre 100 € fait deux fois plus mal que gagner 100 € fait plaisir. Ton cerveau te pousse à « réparer » cette douleur.",
      "Mais l'argent joué est PARTI. Que tu rejoues ou non, il ne reviendra pas. Chaque euro remis en jeu est un NOUVEL euro que tu risques de perdre.",
      "La seule façon de « se refaire », c'est d'arrêter de perdre. Chaque jour sans jouer, tu économises ta mise moyenne. En un mois, ça fait déjà une belle somme. C'est ça, le vrai gain.",
    ],
  },
  {
    id: '10',
    title: 'Exercice : la respiration 4-7-8',
    category: 'exercice',
    categoryLabel: 'Exercices',
    icon: 'barbell-outline',
    readTime: '5 min',
    image: IMAGES.articles.meditation,
    content: [
      "La respiration 4-7-8 est une technique puissante pour calmer une envie en quelques minutes. Elle active le système nerveux parasympathique (le mode « calme »).",
      "Comment faire :\n• Inspire par le nez pendant 4 secondes\n• Retiens ton souffle pendant 7 secondes\n• Expire lentement par la bouche pendant 8 secondes",
      "Répète ce cycle 4 fois. Ça prend moins de 2 minutes.",
      "Pourquoi ça marche : l'envie de jouer active le mode « combat ou fuite » de ton cerveau. La respiration lente envoie le signal inverse : « tout va bien, pas besoin de fuir vers le jeu ».",
      "Pratique cette technique même quand tu n'as pas d'envie. Plus tu la maîtrises en temps normal, plus elle sera efficace en moment de crise.",
    ],
  },
  {
    id: '11',
    title: "Le cycle de l'addiction",
    category: 'mecanisme',
    categoryLabel: 'Comprendre',
    icon: 'brain-outline',
    readTime: '4 min',
    image: IMAGES.articles.cycle,
    content: [
      "L'addiction suit un cycle prévisible en 4 phases : déclencheur → envie → passage à l'acte → culpabilité. Comprendre ce cycle, c'est le premier pas pour le briser.",
      "Phase 1 — Le déclencheur : stress, ennui, pub, passage devant un tabac/PMU, notification d'un site de paris. Quelque chose active le souvenir du jeu.",
      "Phase 2 — L'envie : ton cerveau libère de la dopamine par anticipation. Tu n'as même pas encore joué mais tu ressens déjà l'excitation. L'envie dure en moyenne 15-20 minutes.",
      "Phase 3 — Le passage à l'acte : tu joues. Le soulagement est immédiat mais bref. Très vite, tu en veux plus.",
      "Phase 4 — La culpabilité : regret, honte, promesse de ne plus recommencer... jusqu'au prochain déclencheur. Et le cycle repart.",
      "La clé : intervenir aux phases 1 ou 2. Une fois en phase 3, c'est beaucoup plus dur. Utilise le SOS de l'app dès la phase 2.",
    ],
  },
  {
    id: '12',
    title: 'Les mensonges que le jeu te fait croire',
    category: 'piege',
    categoryLabel: 'Pièges mentaux',
    icon: 'warning-outline',
    readTime: '4 min',
    image: IMAGES.articles.trigger,
    content: [
      "L'addiction est une usine à mensonges. Elle te murmure des choses qui semblent vraies mais qui sont conçues pour te faire replonger.",
      "« Juste une dernière fois » — C'est JAMAIS la dernière fois. Le cerveau addict ne sait pas s'arrêter après un tour. Une mise en appelle dix.",
      "« Je contrôle la situation » — Si tu contrôlais, tu n'aurais pas perdu autant. Le contrôle est une illusion que le jeu entretient.",
      "« Les autres gagnent, pourquoi pas moi » — Les autres perdent aussi, ils n'en parlent pas. Les réseaux sociaux montrent les gains, jamais les pertes.",
      "« C'est mon argent, je fais ce que je veux » — Oui, mais est-ce que tu VEUX perdre ? L'addiction décide à ta place.",
      "Quand une de ces pensées arrive, reconnais-la pour ce qu'elle est : une stratégie de l'addiction, pas ta propre réflexion.",
    ],
  },
  {
    id: '13',
    title: 'Comprendre la dopamine',
    category: 'mecanisme',
    categoryLabel: 'Comprendre',
    icon: 'brain-outline',
    readTime: '5 min',
    image: IMAGES.articles.brain,
    content: [
      "La dopamine n'est pas le « neurotransmetteur du bonheur ». C'est le neurotransmetteur de l'ANTICIPATION. Elle ne te rend pas heureux — elle te pousse à chercher.",
      "Quand tu joues, la dopamine monte AVANT le résultat. C'est l'attente qui excite, pas le gain. C'est pourquoi même les pertes peuvent être excitantes — le moment avant le résultat est le même.",
      "Avec l'addiction, le cerveau libère de moins en moins de dopamine pour les activités normales (manger, socialiser, travailler). Seul le jeu produit assez de dopamine pour « ressentir quelque chose ».",
      "C'est l'anhédonie : l'incapacité à ressentir du plaisir dans les activités du quotidien. C'est temporaire, mais c'est ce qui rend les premières semaines d'arrêt si difficiles.",
      "Bonne nouvelle : en 60-90 jours sans jeu, les récepteurs de dopamine se restaurent. Les activités normales redeviennent plaisantes. Le cerveau guérit.",
    ],
  },
  {
    id: '14',
    title: 'Les casinos en ligne : le danger invisible',
    category: 'piege',
    categoryLabel: 'Pièges mentaux',
    icon: 'warning-outline',
    readTime: '4 min',
    image: IMAGES.articles.finance,
    content: [
      "Les casinos en ligne sont plus dangereux que les casinos physiques. Pourquoi ? Parce qu'ils suppriment toutes les frictions naturelles qui te protègent.",
      "Pas besoin de te déplacer. Pas d'horaires de fermeture. Pas de regard des autres. Tu peux jouer à 3h du matin en pyjama, personne ne saura.",
      "L'argent est dématérialisé : tu ne vois pas les billets partir. Cliquer sur « miser 50 € » fait beaucoup moins mal que poser un billet de 50 € sur une table.",
      "Les bonus de bienvenue, les free spins, les « cashback » — tout est conçu pour te faire déposer une première fois. Après, la machine à addiction prend le relais.",
      "Si tu as un problème avec le jeu en ligne : installe des bloqueurs (Gamban, BetBlocker), fais-toi interdire sur les sites, et supprime les apps. Rends l'accès aussi difficile que possible.",
    ],
  },
  {
    id: '15',
    title: 'Mehdi, 41 ans — « Les paris sportifs ont failli me tuer »',
    category: 'temoignage',
    categoryLabel: 'Témoignages',
    icon: 'people-outline',
    readTime: '5 min',
    image: IMAGES.articles.success,
    content: [
      "« Je suis fan de foot depuis toujours. Quand les applis de paris sont arrivées, j'ai trouvé ça génial. Ça rendait les matchs encore plus excitants. »",
      "« Au début je misais 5-10 euros par match. Puis 50. Puis 200. Au bout d'un an, je misais mon salaire entier le premier du mois. Je me disais que je connaissais le foot, que c'était pas du hasard. »",
      "« J'ai emprunté à ma famille, à des amis, puis à des organismes de crédit. 65 000 euros de dettes. Ma femme a découvert les relevés bancaires. Elle est partie avec nos deux enfants. »",
      "« J'ai pensé au pire. C'est mon frère qui m'a sauvé en m'emmenant aux Joueurs Anonymes. Ça fait 2 ans maintenant. Je rembourse mes dettes, petit à petit. Ma femme et moi on se reparle. »",
      "« Les paris sportifs, c'est le même piège que le casino. Tu crois que tes connaissances te donnent un avantage. Mais le bookmaker a des algorithmes, pas toi. »",
    ],
  },
  {
    id: '16',
    title: 'Léa, 22 ans — « Addict aux jeux en ligne depuis le lycée »',
    category: 'temoignage',
    categoryLabel: 'Témoignages',
    icon: 'people-outline',
    readTime: '4 min',
    image: IMAGES.articles.family,
    content: [
      "« J'ai découvert les jeux de hasard en ligne à 17 ans via une pub Instagram. J'ai menti sur mon âge pour m'inscrire. C'était aussi simple que ça. »",
      "« En terminale, je jouais au lieu de réviser. J'ai raté mon bac. Mes parents pensaient que je passais trop de temps sur les réseaux. Ils ne savaient pas que je perdais 200 € par semaine avec l'argent de mon job étudiant. »",
      "« Le plus dur c'est la honte. À 22 ans, quand tu dis que t'es addict au jeu, les gens te regardent bizarrement. C'est censé être un truc de vieux. Mais l'algorithme des pubs cible les jeunes. »",
      "« J'ai arrêté grâce à un groupe de parole en ligne. Savoir que d'autres jeunes vivaient la même chose m'a aidée à ne plus me sentir seule. Aujourd'hui je reprends mes études. »",
    ],
  },
  {
    id: '17',
    title: 'Exercice : la règle des 15 minutes',
    category: 'exercice',
    categoryLabel: 'Exercices',
    icon: 'barbell-outline',
    readTime: '3 min',
    image: IMAGES.articles.meditation,
    content: [
      "Quand une envie de jouer arrive, ne te dis pas « je ne jouerai plus jamais ». Dis-toi : « j'attends 15 minutes ».",
      "Pourquoi 15 minutes ? Parce que les études montrent qu'une envie intense dure en moyenne 10-20 minutes. Si tu tiens 15 minutes, le pic est passé.",
      "Pendant ces 15 minutes, fais quelque chose : marche, appelle quelqu'un, fais 20 pompes, prends une douche froide, joue à un jeu mobile (non-casino). L'important est d'occuper ton cerveau.",
      "Au bout de 15 minutes, l'envie a probablement baissé. Si elle est encore là, remets 15 minutes. Et encore. Chaque cycle l'affaiblit.",
      "Avec le temps, tu remarqueras que les envies deviennent moins fréquentes ET moins intenses. C'est ton cerveau qui se recâble.",
    ],
  },
  {
    id: '18',
    title: 'Exercice : le bocal des victoires',
    category: 'exercice',
    categoryLabel: 'Exercices',
    icon: 'barbell-outline',
    readTime: '3 min',
    image: IMAGES.articles.nature,
    content: [
      "Prends un bocal (ou une boîte, un tiroir — n'importe quoi). Chaque jour où tu ne joues pas, mets quelque chose dedans.",
      "Ça peut être un papier avec la date, une pièce de 1 €, un bonbon, une bille. L'objet n'a pas d'importance — c'est le geste qui compte.",
      "Visuellement, tu verras le bocal se remplir. C'est une preuve physique, tangible, de tes progrès. Les chiffres sur un écran c'est bien, un bocal plein c'est puissant.",
      "Quand l'envie arrive, regarde le bocal. Chaque objet dedans représente un jour où tu as été plus fort que l'addiction. Tu veux vraiment vider ce bocal ?",
      "Bonus : l'argent que tu n'as PAS joué aujourd'hui, mets-le dans une enveloppe à côté du bocal. Au bout d'un mois, offre-toi quelque chose avec.",
    ],
  },
  {
    id: '19',
    title: "L'effet du joueur : comprendre les probabilités",
    category: 'mecanisme',
    categoryLabel: 'Comprendre',
    icon: 'brain-outline',
    readTime: '4 min',
    image: IMAGES.articles.finance,
    content: [
      "« Rouge est sorti 5 fois de suite, donc noir va forcément sortir ». C'est l'erreur du joueur (gambler's fallacy). Et c'est mathématiquement FAUX.",
      "Chaque tour de roulette est indépendant. La bille n'a pas de mémoire. Après 5 rouges, la probabilité que le prochain soit rouge est EXACTEMENT la même : 48,6%.",
      "Ton cerveau cherche des patterns partout — c'est un avantage évolutif. Mais dans un jeu de hasard, il n'y a PAS de pattern. Il voit des séquences là où il n'y a que du bruit.",
      "Les casinos exploitent ce biais : ils affichent l'historique des résultats (les derniers numéros à la roulette). Ça ne sert à rien pour prédire — mais ça te fait croire que si.",
      "Retiens cette phrase : les événements passés n'influencent pas les événements futurs dans un jeu de hasard. Jamais.",
    ],
  },
  {
    id: '20',
    title: 'Comment le casino est conçu pour te piéger',
    category: 'mecanisme',
    categoryLabel: 'Comprendre',
    icon: 'brain-outline',
    readTime: '5 min',
    image: IMAGES.articles.trigger,
    content: [
      "Rien dans un casino n'est laissé au hasard — sauf le jeu lui-même. Chaque détail est conçu par des psychologues pour te faire jouer plus longtemps.",
      "Pas de fenêtres, pas d'horloges : tu perds la notion du temps. La moquette, la lumière tamisée, la température — tout est calibré pour que tu restes.",
      "Les machines à sous émettent des sons de pièces qui tombent, même pour de petits gains inférieurs à ta mise. Tu as misé 2 € et gagné 0,50 € ? La machine célèbre comme si tu avais touché le jackpot.",
      "Les jetons remplacent l'argent réel. Psychologiquement, miser un jeton de 100 € fait moins mal que miser un billet de 100 €. C'est la même somme, mais la douleur est atténuée.",
      "Les gains sont visibles (lumières, sons, applaudissements). Les pertes sont silencieuses. Tu vois les autres gagner, jamais perdre. Ça crée l'illusion que « tout le monde gagne sauf moi ».",
      "Connaître ces techniques ne te rend pas immunisé — mais ça t'aide à voir le piège pour ce qu'il est.",
    ],
  },
  {
    id: '21',
    title: "L'impact du jeu sur tes proches",
    category: 'mecanisme',
    categoryLabel: 'Comprendre',
    icon: 'brain-outline',
    readTime: '4 min',
    image: IMAGES.articles.family,
    content: [
      "Pour chaque personne addicte au jeu, on estime que 5 à 10 proches sont directement affectés. L'addiction au jeu n'est jamais un problème individuel.",
      "Le mensonge est le premier impact. Tu caches tes pertes, tu inventes des explications pour l'argent manquant. La confiance s'érode, même si tes proches ne savent pas encore pourquoi.",
      "Le stress financier touche tout le foyer : loyer en retard, factures impayées, emprunts cachés. Le conjoint découvre souvent la situation quand elle est déjà grave.",
      "Les enfants ressentent la tension même sans comprendre. L'irritabilité, l'absence mentale, les disputes — tout ça impacte leur développement.",
      "Arrêter de jouer, c'est aussi un cadeau pour les gens que tu aimes. La confiance se reconstruit lentement, mais elle se reconstruit.",
    ],
  },
  {
    id: '22',
    title: 'Exercice : la visualisation du futur',
    category: 'exercice',
    categoryLabel: 'Exercices',
    icon: 'barbell-outline',
    readTime: '5 min',
    image: IMAGES.articles.nature,
    content: [
      "Ferme les yeux. Imagine-toi dans 1 an si tu continues à jouer. Où en es-tu financièrement ? Tes relations ? Ta santé ? Ton travail ? Sois honnête et précis.",
      "Maintenant, imagine-toi dans 1 an si tu arrêtes AUJOURD'HUI. L'argent économisé, la fierté, la confiance retrouvée de tes proches, le sommeil paisible.",
      "Quelle version de toi veux-tu devenir ? Note les deux scénarios sur papier. Garde-les sur toi.",
      "Cette technique s'appelle le « contraste mental ». Les études montrent qu'elle est plus efficace que la simple pensée positive. Voir les deux chemins en même temps renforce ta motivation.",
      "Relis tes deux scénarios chaque matin pendant 21 jours. Ça prend 30 secondes et ça ancre ta décision.",
    ],
  },
  {
    id: '23',
    title: 'Les pièges des bonus et promotions',
    category: 'piege',
    categoryLabel: 'Pièges mentaux',
    icon: 'warning-outline',
    readTime: '3 min',
    image: IMAGES.articles.finance,
    content: [
      "« Bonus de bienvenue 100% : dépose 100 €, joue avec 200 € ! » Ça semble généreux. En réalité, c'est le piège le plus rentable du casino en ligne.",
      "Les conditions de mise (wagering requirements) t'obligent à rejouer le bonus 30 à 50 fois avant de pouvoir retirer. 200 € × 35 = tu dois miser 7 000 € avant de voir ton argent.",
      "Statistiquement, sur 7 000 € misés, le casino en garde 2 à 5% (son avantage). Ton « bonus gratuit » lui rapporte 140-350 €. Le cadeau, c'est LUI qui le reçoit.",
      "Les free spins, cashback, programmes VIP — même logique. Tout est conçu pour te faire déposer et rejouer. Rien n'est gratuit.",
      "La meilleure promotion, c'est celle que tu n'utilises pas.",
    ],
  },
  {
    id: '24',
    title: 'Exercice : construis ton kit anti-envie',
    category: 'exercice',
    categoryLabel: 'Exercices',
    icon: 'barbell-outline',
    readTime: '5 min',
    image: IMAGES.articles.sport,
    content: [
      "Un kit anti-envie est une liste d'actions concrètes, prêtes à l'emploi, pour les moments où l'envie frappe. Prépare-le MAINTENANT, quand tu as les idées claires.",
      "Catégorie CORPS : 20 pompes, douche froide, marcher 10 minutes, respiration 4-7-8, mâcher un chewing-gum fort (menthe poivrée).",
      "Catégorie SOCIAL : appeler un ami (note son numéro ici), envoyer un message dans un groupe de soutien, aller dans un lieu public.",
      "Catégorie MENTAL : relire ta lettre à toi-même, ouvrir cette app et utiliser le SOS, écouter un podcast sur l'addiction, journaliser ce que tu ressens.",
      "Catégorie PLAISIR : regarder un épisode de ta série, jouer à un jeu vidéo, cuisiner quelque chose, écouter de la musique à fond.",
      "Choisis au moins 2 actions par catégorie. Imprime ou note cette liste et garde-la TOUJOURS accessible — dans ton portefeuille, en note sur ton téléphone, sur le frigo.",
    ],
  },
  {
    id: '25',
    title: "L'interdit bancaire volontaire : comment se protéger",
    category: 'mecanisme',
    categoryLabel: 'Comprendre',
    icon: 'brain-outline',
    readTime: '4 min',
    image: IMAGES.articles.finance,
    content: [
      "Quand la volonté ne suffit pas, les barrières concrètes prennent le relais. Voici les outils pour te protéger financièrement.",
      "L'auto-exclusion des casinos : en France, tu peux demander ton interdiction de jeu pour 3 ans (renouvelable) auprès de l'ANJ. C'est gratuit et confidentiel. Ça couvre tous les casinos et sites agréés.",
      "Les bloqueurs de sites : Gamban (payant mais très efficace) et BetBlocker (gratuit) bloquent automatiquement l'accès à des milliers de sites de jeu sur tous tes appareils.",
      "Les limites bancaires : certaines banques permettent de bloquer les paiements vers les opérateurs de jeu. Appelle ta banque et demande.",
      "Confie tes finances : donne temporairement l'accès à tes comptes à une personne de confiance. C'est dur pour l'ego, mais c'est efficace.",
      "Ces barrières ne sont pas un signe de faiblesse. C'est de l'intelligence : tu sais que l'envie sera plus forte que la volonté, alors tu agis quand tu as les idées claires.",
    ],
  },
];
